-- MySQL Script generated by MySQL Workbench
-- dom 22 ago 2021 18:23:21 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecoturismo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecoturismo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci ;
USE `ecoturismo` ;

-- -----------------------------------------------------
-- Table `ecoturismo`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoturismo`.`personas` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(100) NOT NULL,
  `contrasena` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `foto_perfil` TEXT NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;

INSERT INTO `ecoturismo`.`personas`(`usuario`,`contrasena`,`nombre`,`apellido`,`correo`,`foto_perfil`) VALUES 
('acoby', 'acoby123','Andrés','Coby','acoby@gmail.com','https://i.imgur.com/PU4oYy0.png'),
('sennis','sennis123','Sebastián','Ennis','sennis@gmail.com','https://i.imgur.com/hSbI0ZG.jpg'),
('mlalo','mlalo123','Marleen','Lalo','mlalo@gmail.com','https://i.imgur.com/xMuRwzN.jpg'),
('cremington','cremington123','Cherilyn','Remington','cremington@gmail.com','https://i.imgur.com/phKiK9A.jpg'),
('dcelso','dcelso123','Dexter','Celso','dcelso@gmail.com','https://i.imgur.com/7eriQEO.jpg');

-- -----------------------------------------------------
-- Table `ecoturismo`.`publicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoturismo`.`publicaciones` (
  `id_publicacion` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `likes` INT NULL DEFAULT '0',
  PRIMARY KEY (`id_publicacion`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `publicaciones_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ecoturismo`.`personas` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;

alter table publicaciones add (
imagen_representativa TEXT NOT NULL);

alter table publicaciones add(
id_foto INT NOT NULL);


UPDATE `ecoturismo`.`publicaciones` SET `imagen_representativa` = 'https://i.imgur.com/iP8MxbU.jpg' WHERE (`id_publicacion` = '1');
UPDATE `ecoturismo`.`publicaciones` SET `imagen_representativa` = 'https://i.imgur.com/L7lg7iN.jpg' WHERE (`id_publicacion` = '2');
UPDATE `ecoturismo`.`publicaciones` SET `imagen_representativa` = 'https://i.imgur.com/DZtEmnJ.jpg' WHERE (`id_publicacion` = '3');
UPDATE `ecoturismo`.`publicaciones` SET `imagen_representativa` = 'https://i.imgur.com/3C8AAin.jpg' WHERE (`id_publicacion` = '4');

UPDATE `ecoturismo`.`publicaciones` SET `id_foto` = '1' WHERE (`id_publicacion` = '1');
UPDATE `ecoturismo`.`publicaciones` SET `id_foto` = '6' WHERE (`id_publicacion` = '2');
UPDATE `ecoturismo`.`publicacio nes` SET `id_foto` = '10' WHERE (`id_publicacion` = '3');
UPDATE `ecoturismo`.`publicaciones` SET `id_foto` = '14' WHERE (`id_publicacion` = '4');

alter table publicaciones add (
region TEXT NOT NULL);


UPDATE `ecoturismo`.`publicaciones` SET `region` = 'costa' WHERE (`id_publicacion` = '1');
UPDATE `ecoturismo`.`publicaciones` SET `region` = 'sierra' WHERE (`id_publicacion` = '2');
UPDATE `ecoturismo`.`publicaciones` SET `region` = 'oriente' WHERE (`id_publicacion` = '3');
UPDATE `ecoturismo`.`publicaciones` SET `region` = 'costa' WHERE (`id_publicacion` = '4');


INSERT INTO `ecoturismo`.`publicaciones`(`id_usuario`,`nombre`,`likes`) VALUES
(1,'Aventura en el Spondilus',3),
(2,'La Mitad del Mundo',2),
(3,'El Libertador',5),
(4,'Yaku Ñamby',1);


-- -----------------------------------------------------
-- Table `ecoturismo`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoturismo`.`comentarios` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT NOT NULL,
  `id_usuario` INT NULL,
  `id_publicacion` INT NULL,
  PRIMARY KEY (`id_comentario`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `id_publicacion` (`id_publicacion` ASC) VISIBLE,
  CONSTRAINT `comentarios_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ecoturismo`.`personas` (`id_usuario`),
  CONSTRAINT `comentarios_ibfk_2`
    FOREIGN KEY (`id_publicacion`)
    REFERENCES `ecoturismo`.`publicaciones` (`id_publicacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;

INSERT INTO `ecoturismo`.`comentarios`(`contenido`,`id_usuario`,`id_publicacion`) VALUES
/*Ruta Spondilus*/ ('It is a very nice and quiet place to enjoy with friends the best beaches in Ecuador for its blue and transparent water.',1,1),
/*Ruta Spondilus*/('Salinas is a very accommodating little town on the beach in Ecuador.',2,1),
/*Ruta Mitad del Mundo*/('The city of Quito is both historic and modern. The "new" part of the city has very nice hotels, reasonably priced, and plenty of quality restaurants.',3,2),
/*Ruta Libertador*/('Places to see, ways to wander, and signature experiences.',4,3),
/*Ruta Yaku Ñamby*/('I have just come back from 3 days at the Napo Cultural Centre in January 2020 and it was the best experience of my life. The activities are well planned and organised and incredibly interesting and fun.',5,4);

-- -----------------------------------------------------
-- Table `ecoturismo`.`etiquetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoturismo`.`etiquetas` (
  `id_etiqueta` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_etiqueta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;

INSERT INTO `ecoturismo`.`etiquetas`(`nombre`) VALUES
('fun'),('beach'),('accesible'),('comida'),('animales');

-- -----------------------------------------------------
-- Table `ecoturismo`.`rutas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoturismo`.`rutas` (
  `id_ruta` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `duracion` VARCHAR(100) NOT NULL,
  `id_publicacion` INT NOT NULL,
  PRIMARY KEY (`id_ruta`),
  INDEX `id_publicacion` (`id_publicacion` ASC) VISIBLE,
  CONSTRAINT `rutas_ibfk_1`
    FOREIGN KEY (`id_publicacion`)
    REFERENCES `ecoturismo`.`publicaciones` (`id_publicacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;

INSERT INTO `ecoturismo`.`rutas`(`nombre`,`duracion`,`id_publicacion`) VALUES
('Ruta del Spondilus','2 semanas',1),
('Ruta del Tren de la Mitad del Mundo','1 semana',2),
('Ruta del Libertador','5 días',3),
('Ruta del Agua o Yaky Ñamby','2 semanas',4);

-- -----------------------------------------------------
-- Table `ecoturismo`.`lugares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoturismo`.`lugares` (
  `id_lugar` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `coordenadas` VARCHAR(100) NOT NULL,
  `id_ruta` INT NOT NULL,
  PRIMARY KEY (`id_lugar`),
  INDEX `id_ruta` (`id_ruta` ASC) VISIBLE,
  CONSTRAINT `lugares_ibfk_1`
    FOREIGN KEY (`id_ruta`)
    REFERENCES `ecoturismo`.`rutas` (`id_ruta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;

INSERT INTO `ecoturismo`.`lugares`(`nombre`,`coordenadas`,`id_ruta`) VALUES 
/*Ruta Spondilus*/('Salinas','-2.2055574942175413,-80.9672891324658',1),
('Ayangue','-1.9831155908472597,-80.7514682096297',1),
('Montañita','-1.8207401325205217,-80.75439161066328',1),
('Puerto López','-1.5506878688677947,-80.8116161185263',1),
('Manta','-0.9412838040170762,-80.73005650126149',1),
/*Ruta Mitad del Mundo*/('Tambo','-2.5099397719023746,-78.92773215803734',2),
('Riobamba','-1.6496283751404748,-78.6605100634994',2),
('Quito','-0.17515150874215185,-78.46061706413911',2),
('Ibarra','0.34758267526675496,-78.1289256261971',2),
/*Ruta Libertador*/('Parque Nacional Cotopaxi','-0.7008558808294457,-78.42929931088642',3),
('El Boliche','-0.7952251951824737,-78.5429778864975',3),
('Laguna de Yambo','-1.1010383853926735,-78.58853533280988',3),
('La cara de piedra de Angamarca','-0.25828788272143083,-78.55355157357893',3),
/*Ruta Yaku Ñamby*/('Sucumbíos','0.07561070153620837,-76.95589816019142',4),
('Napo','-0.5174290150996121,-78.12221115374854',4),
('Morona Santiago','-1.4787395709765587,-77.99997047207103',4),
('Zamora Chinchipe','-4.063270910462459,-78.95686279297236',4);

-- -----------------------------------------------------
-- Table `ecoturismo`.`fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoturismo`.`fotos` (
  `id_foto` INT NOT NULL AUTO_INCREMENT,
  `url` TEXT NOT NULL,
  `id_lugar` INT NOT NULL,
  PRIMARY KEY (`id_foto`),
  INDEX `id_lugar` (`id_lugar` ASC) VISIBLE,
  CONSTRAINT `fotos_ibfk_1`
    FOREIGN KEY (`id_lugar`)
    REFERENCES `ecoturismo`.`lugares` (`id_lugar`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;

INSERT INTO `ecoturismo`.`fotos`(`url`,`id_lugar`) VALUES 
('https://i.imgur.com/iP8MxbU.jpg',1),
('https://i.imgur.com/79d2vKE.jpg',2),
('https://i.imgur.com/S8MpuL0.jpg',3),
('https://i.imgur.com/jQjOomN.jpg',4),
('https://i.imgur.com/lOnbz6y.jpg',5),
('https://i.imgur.com/L7lg7iN.jpg',6),
('https://i.imgur.com/zThaZZx.jpg',7),
('https://i.imgur.com/svgR6a4.jpg',8),
('https://i.imgur.com/6yvIAnW.jpg',9),
('https://i.imgur.com/DZtEmnJ.jpg',10),
('https://i.imgur.com/6kHrnF1.jpg',11),
('https://i.imgur.com/paYAIPH.jpg',12),
('https://i.imgur.com/jmTusTk.jpg',13),
('https://i.imgur.com/3C8AAin.jpg',14),
('https://i.imgur.com/X9vX14Z.jpg',15),
('https://i.imgur.com/355aJYY.jpg',16),
('https://i.imgur.com/oinBFGv.jpg',17);

-- -----------------------------------------------------
-- Table `ecoturismo`.`rel_rutaTag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoturismo`.`rel_rutaTag` (
  `id_ruta` INT NULL,
  `id_etiqueta` INT NULL,
  INDEX `id_ruta` (`id_ruta` ASC) VISIBLE,
  INDEX `id_etiqueta` (`id_etiqueta` ASC) VISIBLE,
  CONSTRAINT `rel_rutaTag_ibfk_1`
    FOREIGN KEY (`id_ruta`)
    REFERENCES `ecoturismo`.`rutas` (`id_ruta`),
  CONSTRAINT `rel_rutaTag_ibfk_2`
    FOREIGN KEY (`id_etiqueta`)
    REFERENCES `ecoturismo`.`etiquetas` (`id_etiqueta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;

INSERT INTO `ecoturismo`.`rel_rutaTag`(`id_ruta`,`id_etiqueta`) VALUES 
(1,1),(1,2),(1,4),
(2,4),(2,5),
(3,3),
(4,1),(4,5);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
